front_homepage:
    path:     /
    defaults: { _controller: FrontBundle:Default:index }
layout:
    path:     /layout
    defaults: { _controller: FrontBundle:Default:layout }
afficherCatalogue:
    path:     /afficherCatalogue
    defaults: { _controller: FrontBundle:Produit:afficherCatalogue }


afficherPanier:
    path:     /afficherPanier
    defaults: { _controller: FrontBundle:Panier:afficherPanier }

DQLtotal:
    path:     /DQL
    defaults: {_controller: FrontBundle:Panier:DQLtotal }


addtocart:
    path:     /addtocart/{id}
    defaults: { _controller: FrontBundle:Panier:addtocart }

modifierPanier :
    path:     /modifierPanier/{id}
    defaults: { _controller: FrontBundle:Panier:modifierPanier }

supprimerPanier :
    path:     /supprimerPanier/{id}
    defaults: { _controller: FrontBundle:Panier:supprimerPanier }

afficherFavoris:
    path:     /afficherFavoris
    defaults: { _controller: FrontBundle:Favoris:afficherFavoris }

addtofavoris:
    path:     /addtofavoris/{id}
    defaults: { _controller: FrontBundle:Favoris:addtofavoris }

supprimerFavoris :
    path:     /supprimerFavoris/{id}
    defaults: { _controller: FrontBundle:Favoris:supprimerFavoris }

