front_homepage:
    path:     /
    defaults: { _controller: FrontBundle:Default:index }
layout:
    path:     /layout
    defaults: { _controller: FrontBundle:Default:layout }
afficher_Produit:
    path:     /afficherProduit
    defaults: { _controller: FrontBundle:Produit:afficherProduit }