front_homepage:
    path:     /
    defaults: { _controller: FrontBundle:Default:index }
layout:
    path:     /layout
    defaults: { _controller: FrontBundle:Default:layout }
afficherCatalogue:
    path:     /afficherCatalogue
    defaults: { _controller: FrontBundle:Produit:afficherCatalogue }


afficherPanier:
    path:     /afficherPanier
    defaults: { _controller: FrontBundle:Panier:afficherPanier }

DQLtotal:
    path:     /DQL
    defaults: {_controller: FrontBundle:Panier:DQLtotal }


addtocart:
    path:     /addtocart/{id}
    defaults: { _controller: FrontBundle:Panier:addtocart }

modifierPanierplus :
    path:     /modifierPanierplus/{id}
    defaults: { _controller: FrontBundle:Panier:modifierPanierplus }

modifierPaniermoins :
    path:     /modifierPaniermoins/{id}
    defaults: { _controller: FrontBundle:Panier:modifierPaniermoins }

supprimerPanier :
    path:     /supprimerPanier/{id}
    defaults: { _controller: FrontBundle:Panier:supprimerPanier }

afficherFavoris:
    path:     /afficherFavoris
    defaults: { _controller: FrontBundle:Favoris:afficherFavoris }

addtofavoris:
    path:     /addtofavoris/{id}
    defaults: { _controller: FrontBundle:Favoris:addtofavoris }

supprimerFavoris :
    path:     /supprimerFavoris/{id}
    defaults: { _controller: FrontBundle:Favoris:supprimerFavoris }
rechercherCatalogue:
    path:     /rechercherCatalogue
    defaults: { _controller: FrontBundle:Produit:rechercherCatalogue }
afficherCategorieFleur:
    path:     /afficherCategorieFleur
    defaults: { _controller: FrontBundle:Produit:afficherCategorieFleur }
afficherCategoriePlantes:
    path:     /afficherCategoriePlantes
    defaults: { _controller: FrontBundle:Produit:afficherCategoriePlantes }

ajouterService:
    path:     /ajouterService
    defaults: { _controller: FrontBundle:Service:ajouterService }
afficherDetailsProduit:
    path:     /afficherDetailsProduit/{id}
    defaults: { _controller: FrontBundle:Produit:afficherDetailsProduit }

ajouterCommande:
    path:     /ajouterCommande
    defaults: { _controller: FrontBundle:Panier:ajouterCommande }

afficherCommande:
    path:     /afficherCommande
    defaults: { _controller: FrontBundle:Commande:afficherCommande }