back_homepage:
    path:     /
    defaults: { _controller: BackBundle:Default:index }
ajouter_livreur:
    path:     /ajouterlivreur
    defaults: { _controller: BackBundle:Livreur:ajouterlivreur }


afficher_livreur:
    path:     /afficherlivreur
    defaults: { _controller: BackBundle:Livreur:afficherlivreur }


supprimerLivreur :
    path:     /supprimerLivreur/{id}
    defaults: { _controller: BackBundle:Livreur:supprimerLivreur }
modifierLivreur :
    path:     /modifierLivreur/{id}
    defaults: { _controller: BackBundle:Livreur:modifierLivreur }

ajouter_Produit:
    path:     /ajouterProduit
    defaults: { _controller: BackBundle:Produit:ajouterProduit }
afficher_Produit:
    path:     /afficherProduit
    defaults: { _controller: BackBundle:Produit:afficherProduit }
supprimerProduit :
    path:     /supprimerProduit/{id}
    defaults: { _controller: BackBundle:Produit:supprimerProduit }
modifierProduit :
    path:     /modifierProduit/{id}
    defaults: { _controller: BackBundle:Produit:modifierProduit }


afficher_commande:
    path:     /affichercommande
    defaults: { _controller: BackBundle:Commande:affichercommande }


supprimerCommande :
    path:     /supprimerCommande/{id}
    defaults: { _controller: BackBundle:Commande:supprimerCommande }

modifierCommande :
    path:     /modifierCommande/{id}
    defaults: { _controller: BackBundle:Commande:modifierCommande }
afficher_Catalogue:
    path:     /afficherCatalogue
    defaults: { _controller: BackBundle:Produit:afficherCatalogue }
ajouter_Produit_Catalogue:
    path:     /ajouterProduitCatalogue/{id}
    defaults: { _controller: BackBundle:Produit:ajouterProduitCatalogue }
supprimerProduitCatalogue :
    path:     /supprimerProduitCatalogue/{id}
    defaults: { _controller: BackBundle:Produit:supprimerProduitCatalogue }
modifierProduitCatalogue :
    path:     /modifierProduitCatalogue/{id}
    defaults: { _controller: BackBundle:Produit:modifierProduitCatalogue }

ajouter_jardinier:
    path:     /ajouterJardinier
    defaults: { _controller: BackBundle:Jardinier:ajouterJardinier }
afficher_jardinier:
    path:     /afficherJardinier
    defaults: { _controller: BackBundle:Jardinier:afficherJardinier }
supprimerJardinier :
    path:     /supprimerJardinier/{id}
    defaults: { _controller: BackBundle:Jardinier:supprimerJardinier }
modifierJardinier :
    path:     /modifierJardinier/{id}
    defaults: { _controller: BackBundle:Jardinier:modifierJardinier }