back_homepage:
    path:     /
    defaults: { _controller: BackBundle:Default:index }
ajouter_livreur:
    path:     /ajouterlivreur
    defaults: { _controller: BackBundle:Livreur:ajouterlivreur }


afficher_livreur:
    path:     /afficherlivreur
    defaults: { _controller: BackBundle:Livreur:afficherlivreur }


supprimerLivreur :
    path:     /supprimerLivreur/{id}
    defaults: { _controller: BackBundle:Livreur:supprimerLivreur }
modifierLivreur :
    path:     /modifierLivreur/{id}
    defaults: { _controller: BackBundle:Livreur:modifierLivreur }

ajouter_Produit:
    path:     /ajouterProduit
    defaults: { _controller: BackBundle:Produit:ajouterProduit }
afficher_Produit:
    path:     /afficherProduit
    defaults: { _controller: BackBundle:Produit:afficherProduit }
supprimerProduit :
    path:     /supprimerProduit/{id}
    defaults: { _controller: BackBundle:Produit:supprimerProduit }
modifierProduit :
    path:     /modifierProduit/{id}
    defaults: { _controller: BackBundle:Produit:modifierProduit }
PdfProduit:
    path:     /PdfProduit
    defaults: { _controller: BackBundle:Produit:PdfProduit }


afficher_commande:
    path:     /affichercommande
    defaults: { _controller: BackBundle:Commande:affichercommande }


supprimerCommande :
    path:     /supprimerCommande/{id}
    defaults: { _controller: BackBundle:Commande:supprimerCommande }

modifierCommande :
    path:     /modifierCommande/{id}
    defaults: { _controller: BackBundle:Commande:modifierCommande }
afficher_Catalogue:
    path:     /afficherCatalogue
    defaults: { _controller: BackBundle:Produit:afficherCatalogue }
ajouter_Produit_Catalogue:
    path:     /ajouterProduitCatalogue/{id}
    defaults: { _controller: BackBundle:Produit:ajouterProduitCatalogue }
supprimerProduitCatalogue :
    path:     /supprimerProduitCatalogue/{id}
    defaults: { _controller: BackBundle:Produit:supprimerProduitCatalogue }
modifierProduitCatalogue :
    path:     /modifierProduitCatalogue/{id}
    defaults: { _controller: BackBundle:Produit:modifierProduitCatalogue }

ajouter_jardinier:
    path:     /ajouterJardinier
    defaults: { _controller: BackBundle:Jardinier:ajouterJardinier }
afficher_jardinier:
    path:     /afficherJardinier
    defaults: { _controller: BackBundle:Jardinier:afficherJardinier }
supprimerJardinier :
    path:     /supprimerJardinier/{id}
    defaults: { _controller: BackBundle:Jardinier:supprimerJardinier }
modifierJardinier :
    path:     /modifierJardinier/{id}
    defaults: { _controller: BackBundle:Jardinier:modifierJardinier }
afficherVoucher :
    path:     /afficherVoucher
    defaults: { _controller: BackBundle:Voucher:afficherVoucher }
supprimerVoucher :
    path:     /supprimerVoucher/{vouchercode}
    defaults: { _controller: BackBundle:Voucher:supprimerVoucher }
modifierVoucher :
    path:     /modifierVoucher/{vouchercode}
    defaults: { _controller: BackBundle:Voucher:modifierVoucher }
ajouterVoucher :
    path:     /ajouterVoucher
    defaults: { _controller: BackBundle:Voucher:ajouterVoucher }

afficherOffre :
    path:     /afficherOffre
    defaults: { _controller: BackBundle:Offre:afficherOffre }
supprimerOffre :
    path:     /supprimerOffre/{id}
    defaults: { _controller: BackBundle:Offre:supprimerOffre }
modifierOffre :
    path:     /modifierOffre/{id}
    defaults: { _controller: BackBundle:Offre:modifierOffre }
ajouterOffre :
    path:     /ajouterOffre
    defaults: { _controller: BackBundle:Offre:ajouterOffre }

afficher_service:
    path:     /afficher_Service
    defaults: { _controller: BackBundle:Services:afficherService }
completer_service:
    path:     /completer_Service
    defaults: { _controller: BackBundle:Services:affecterService }

details_jardinier:
    path:     /details_jardinier/{id}
    defaults: { _controller: BackBundle:Jardinier:detailsJardinier }
chartProduit:
    path:     /chartProduit
    defaults: { _controller: BackBundle:Produit:chartProduit }
MoinsQuantite:
    path:     /MoinsQuantite
    defaults: { _controller: BackBundle:Produit:MoinsQuantite }

