<?php

namespace BackBundle\Repository;

/**
 * UtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends \Doctrine\ORM\EntityRepository
{
    public function StatDQL()
    {
        $query = $this->getEntityManager()->createQuery('select count(c.idCommande) as Com,c.etat as Etat from BackBundle:Commande c GROUP BY c.etat');


         $resultat = $query->getArrayResult();
         $data = array();
        foreach ($resultat as $values)
        {
            $a = array($values['Etat'],intval($values['Com']));
            array_push($data,$a);
        }
        return $data;

    }

    public function StatvilleDQL()
    {
        $query = $this->getEntityManager()->createQuery('select count(c.idCommande) as Com,c.ville as ville from BackBundle:Commande c GROUP BY c.ville');


        $resultat = $query->getArrayResult();
        $data = array();
        foreach ($resultat as $values)
        {
            $a = array($values['ville'],intval($values['Com']));
            array_push($data,$a);
        }
        return $data;

    }
}
