<?php

namespace BackBundle\Repository;

/**
 * UtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LivreurRepository extends \Doctrine\ORM\EntityRepository
{
    public function StatlivDQL()
    {
        $query = $this->getEntityManager()->createQuery('select count(c.idLivreur) as Liv,c.disponibilite as dispo from BackBundle:Livreur c GROUP BY c.disponibilite');


         $resultat = $query->getArrayResult();
         $data = array();
        foreach ($resultat as $values)
        {
            $a = array($values['dispo'],$values['Liv']);
            array_push($data,$a);
        }
        return $data;

    }
}
