<?php

namespace BackBundle\Repository;

/**
 * UtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LivreurRepository extends \Doctrine\ORM\EntityRepository
{
    public function StatlivDQL()
    {
        $query = $this->getEntityManager()->createQuery('select count(c.idLivreur) as Liv,c.disponibilite as dispo from BackBundle:Livreur c GROUP BY c.disponibilite');


         $resultat = $query->getResult();
        $datas = array();
        foreach ($resultat as $values)
        {
            $a = array($values['dispo'],intval($values['Liv']));
            array_push($datas,$a);
        }
        return $datas;


    }
    public function LivreurDQL()
    {
        $query = $this->getEntityManager()->createQuery("select c.nomLivreur as nom from BackBundle:Livreur c where c.disponibilite='Disponible'");


        $resultat = $query->getArrayResult();

        return $resultat;

    }
}
